import re
import os
import tempfile
from datetime import datetime

from fpdf import FPDF


def _clean(text: str) -> str:
    """Strip markdown and non-latin characters so fpdf core fonts don't crash."""
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'#{1,6}\s*', '', text)
    text = re.sub(r'`{1,3}.*?`{1,3}', '', text, flags=re.DOTALL)
    text = re.sub(r'\[(.*?)\]\(.*?\)', r'\1', text)
    text = re.sub(r'-{3,}', '-' * 40, text)
    # Remove characters outside latin-1 range (emojis, devanagari etc.)
    text = text.encode('latin-1', errors='ignore').decode('latin-1')
    return text.strip()


_SEV_RGB = {
    "EMERGENCY": (220, 38, 38),
    "SEVERE":    (234, 88, 12),
    "MODERATE":  (161, 98, 7),
    "MILD":      (22, 101, 52),
}


class _Report(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(30, 100, 210)
        self.cell(0, 14, "AI Medical Assistant", ln=True, align="C")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, "Confidential Medical Consultation Report", ln=True, align="C")
        self.set_draw_color(30, 100, 210)
        self.set_line_width(0.6)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(
            0, 8,
            "AI Medical Assistant  |  For educational purposes only  |  "
            f"Page {self.page_no()}",
            align="C",
        )


def generate_report(messages: list, severity: str = "MILD", city: str = "") -> bytes:
    """
    Generate a PDF report of the conversation and return raw bytes.

    Parameters
    ----------
    messages  : list of {"role": "user"/"assistant", "content": str}
    severity  : worst severity seen in the session
    city      : detected patient location
    """
    pdf = _Report()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=18)

    # ── Meta block ────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    now = datetime.now().strftime("%d %B %Y  %I:%M %p")
    pdf.cell(0, 7, f"Date & Time : {now}", ln=True)
    if city:
        pdf.cell(0, 7, f"Location    : {city}", ln=True)

    # Severity pill
    r, g, b = _SEV_RGB.get(severity, (22, 101, 52))
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(r, g, b)
    pdf.cell(0, 8, f"Severity    : {severity}", ln=True)
    pdf.ln(4)

    # ── Section heading ───────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(0, 9, "Consultation Transcript", ln=True)
    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.3)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # ── Messages ──────────────────────────────────────────────────────────────
    for msg in messages:
        role = msg.get("role", "")
        content = _clean(msg.get("content", ""))
        if not content:
            continue

        if role == "user":
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(30, 100, 210)
            pdf.cell(0, 7, "Patient", ln=True)
        else:
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(0, 130, 70)
            pdf.cell(0, 7, "AI Medical Assistant", ln=True)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        pdf.multi_cell(0, 5.5, content)
        pdf.ln(3)

    # ── Disclaimer ────────────────────────────────────────────────────────────
    pdf.ln(6)
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        0, 5,
        "DISCLAIMER: This report is generated by an AI system and is provided for "
        "educational and reference purposes only. It does not constitute a medical "
        "diagnosis or professional medical advice. Always consult a qualified healthcare "
        "professional before making any medical decisions.",
        fill=True,
    )

    # ── Output to bytes ───────────────────────────────────────────────────────
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    tmp.close()
    try:
        pdf.output(tmp.name)
        with open(tmp.name, "rb") as f:
            return f.read()
    finally:
        os.unlink(tmp.name)
